-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 00:04:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema esm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esm_db` DEFAULT CHARACTER SET utf8 ;
USE `esm_db` ;

-- -----------------------------------------------------
-- Table `esm_db`.`survey_creator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`survey_creator` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 441
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`survey` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `createdAt` VARCHAR(45) NULL DEFAULT NULL,
  `updatedAt` VARCHAR(45) NULL DEFAULT NULL,
  `frequency` TINYINT(4) NULL DEFAULT NULL,
  `is_test` TINYINT(4) NULL DEFAULT NULL,
  `start` VARCHAR(45) NULL DEFAULT NULL,
  `end` VARCHAR(45) NULL DEFAULT NULL,
  `is_shared` TINYINT(4) NULL DEFAULT NULL,
  `access_code` VARCHAR(100) NULL DEFAULT NULL,
  `anonymity` TINYINT(4) NULL DEFAULT NULL,
  `desc_media` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `access_code_UNIQUE` (`access_code` ASC) VISIBLE,
  INDEX `creator_id_idx` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `creator_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `esm_db`.`survey_creator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1401
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`survey_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`survey_section` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `survey_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `is_random` TINYINT(4) NULL DEFAULT NULL,
  `order_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `survey_id_idx` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `survey_id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `esm_db`.`survey` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1431
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`survey_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`survey_question` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `section_id` INT(11) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `question` LONGTEXT NULL DEFAULT NULL,
  `desc` VARCHAR(100) NULL DEFAULT NULL,
  `choices` LONGTEXT NULL DEFAULT NULL,
  `order_id` INT(11) NULL DEFAULT NULL,
  `is_required` TINYINT(4) NULL DEFAULT NULL,
  `desc_media` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `section_id_idx` (`section_id` ASC) VISIBLE,
  CONSTRAINT `section_id`
    FOREIGN KEY (`section_id`)
    REFERENCES `esm_db`.`survey_section` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3001
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`anonymous_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`anonymous_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`anonymous_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`anonymous_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `respondent_id` VARCHAR(100) NULL DEFAULT NULL,
  `survey_id` INT(11) NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `anonymous_survey_id_idx` (`survey_id` ASC) VISIBLE,
  INDEX `anonymous_res_id_idx` (`respondent_id` ASC) VISIBLE,
  CONSTRAINT `anonymous_survey_id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `esm_db`.`survey` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `anoymous_res_id`
    FOREIGN KEY (`respondent_id`)
    REFERENCES `esm_db`.`anonymous_users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`anonymous_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`anonymous_answer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NULL DEFAULT NULL,
  `answer` LONGTEXT NULL DEFAULT NULL,
  `record_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `anonymous_record_id_idx` (`record_id` ASC) VISIBLE,
  INDEX `anonymous_question_id_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `anonymous_question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `esm_db`.`survey_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `anonymous_record_id`
    FOREIGN KEY (`record_id`)
    REFERENCES `esm_db`.`anonymous_record` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 841
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`change_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`change_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `createdAt` VARCHAR(45) NULL DEFAULT NULL,
  `updatedAt` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `change_type` VARCHAR(45) NULL DEFAULT NULL,
  `table_name` VARCHAR(45) NULL DEFAULT NULL,
  `table_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1561
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`client_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`client_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` CHAR(100) NULL DEFAULT NULL,
  `therapist_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `therapist_id_idx` (`therapist_id` ASC) VISIBLE,
  CONSTRAINT `therapist_id`
    FOREIGN KEY (`therapist_id`)
    REFERENCES `esm_db`.`survey_creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 511
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`client_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`client_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `respondent_id` INT(11) NULL DEFAULT NULL,
  `survey_id` INT(11) NULL DEFAULT NULL,
  `timestamp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `res_survey_id_idx` (`survey_id` ASC) VISIBLE,
  INDEX `respondent_id_idx` (`respondent_id` ASC) VISIBLE,
  CONSTRAINT `res_survey_id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `esm_db`.`survey` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `respondent_id`
    FOREIGN KEY (`respondent_id`)
    REFERENCES `esm_db`.`client_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 171
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`client_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`client_answer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `question_id` INT(11) NULL DEFAULT NULL,
  `answer` LONGTEXT NULL DEFAULT NULL,
  `record_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `question_id_idx` (`question_id` ASC) VISIBLE,
  INDEX `record_id_idx` (`record_id` ASC) VISIBLE,
  CONSTRAINT `question_id`
    FOREIGN KEY (`question_id`)
    REFERENCES `esm_db`.`survey_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `record_id`
    FOREIGN KEY (`record_id`)
    REFERENCES `esm_db`.`client_record` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 951
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `esm_db`.`collaboration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esm_db`.`collaboration` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `survey_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_collab_idx` (`user_id` ASC) VISIBLE,
  INDEX `survey_id_collab_idx` (`survey_id` ASC) VISIBLE,
  CONSTRAINT `survey_id_collab`
    FOREIGN KEY (`survey_id`)
    REFERENCES `esm_db`.`survey` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_id_collab`
    FOREIGN KEY (`user_id`)
    REFERENCES `esm_db`.`survey_creator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 951
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
